FROM --platform=linux/amd64 eclipse-temurin:17-jdk-alpine
ARG JAR_FILE=./target/gpd*.jar

EXPOSE 8080

COPY ${JAR_FILE} /home/application.jar
ENTRYPOINT ["java", "-Dserver.port=8080", "-jar", "/home/application.jar"]
