FROM  adoptopenjdk/openjdk11:jdk-11.0.9.1_1-alpine
ARG JAR_FILE=./target/payments*.jar
ARG AI_AGENT=./applicationinsights-agent*jar
ARG AI_CONF=./applicationinsights.json

EXPOSE 80
WORKDIR /home
COPY ${JAR_FILE} application.jar
COPY ${AI_AGENT} applicationinsights-agent.jar
COPY ${AI_CONF}  applicationinsights.json

ENTRYPOINT ["java", "-Dserver.port=80", "-jar", "application.jar", "-javaagent:applicationinsights-agent.jar" ]
