properties.environment=local

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)

# Scheduling configuration
cron.job.schedule.enabled=true
cron.job.schedule.expression.valid.status=*/35 * * * * *
cron.job.schedule.expression.expired.status=*/35 * * * * *


# Flyway settings 
spring.flyway.schemas=apd

logging.level.root=INFO
logging.level.org.springframework.web=INFO
