# Upgrades the version numbers as reported in pom files

parameters:
  # Versioning parameters
  - name: 'semver'
    type: string
    values:
      - major
      - minor
      - patch
      - buildNumber
      - skip
  - name: 'subproject'
    type: string


steps:
  - ${{ if eq(parameters.semver, 'patch') }}:
      - task: Maven@3
        inputs:
          mavenPomFile: "${{parameters.subproject}}/pom.xml"
          goals: 'build-helper:parse-version versions:set'
          options: '-DnewVersion=${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}'
  - ${{ if eq(parameters.semver, 'minor') }}:
      - task: Maven@3
        inputs:
          mavenPomFile: "${{parameters.subproject}}/pom.xml"
          goals: 'build-helper:parse-version versions:set'
          options: '-DnewVersion=${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}.0'
  - ${{ if eq(parameters.semver, 'major') }}:
      - task: Maven@3
        inputs:
          mavenPomFile: "${{parameters.subproject}}/pom.xml"
          goals: 'build-helper:parse-version versions:set'
          options: '-DnewVersion=${parsedVersion.nextMajorVersion}.0.0'
  - ${{ if eq(parameters.semver, 'buildNumber') }}:
      - task: Maven@3
        inputs:
          mavenPomFile: "${{parameters.subproject}}/pom.xml"
          goals: 'build-helper:parse-version versions:set'
          options: '-DnewVersion=${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}-${parsedVersion.nextBuildNumber}'
