apiVersion: v2
name: pagopa-gpd-core
description: micro-service to manage Creditor Institution debtor positions
type: application
version: 0.303.0
appVersion: 1.1.29-PIDM-1820-hikari-pool-connection-leak
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
