apiVersion: v2
name: pagopa-gpd-core
description: micro-service to manage Creditor Institution debtor positions
type: application
version: 0.307.0
appVersion: 1.1.32-1-fix-unpinned-tag
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
