microservice-chart:
  namespace: "gps"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-debt-position
    tag: "0.6.16"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 15
    failureThreshold: 10
    periodSeconds: 5
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 15
    failureThreshold: 10
    periodSeconds: 5
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 8080
  ingress:
    create: true
    host: "weuuat.gps.internal.uat.platform.pagopa.it"
    path: /pagopa-gpd-core/(.*)
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "1024Mi"
      cpu: "0.75"
    limits:
      memory: "1024Mi"
      cpu: "0.75"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 7
    pollingInterval: 1 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "50"
      - type: metrics-api
        metadata:
          targetValue: "50" # milliseconds
          url: "https://weuuat.gps.internal.uat.platform.pagopa.it/pagopa-gpd-core/actuator/metrics/http.server.requests.percentile?tag=phi:0.99"
          valueLocation: "measurements.0.value"
    advanced:
      horizontalPodAutoscalerConfig:
        behavior:
          scaleDown:
            # https://github.com/kubernetes/enhancements/blob/master/keps/sig-autoscaling/853-configurable-hpa-scale-velocity/README.md#stabilization-window
            stabilizationWindowSeconds: 300
            policies:
              - type: Pods
                value: 1
                periodSeconds: 20
          scaleUp:
            stabilizationWindowSeconds: 0
            policies:
              - type: Pods
                value: 2
                periodSeconds: 20
  envConfig:
    WEBSITE_SITE_NAME: 'pagopa-u-gpd-core-service'
    ENV: 'Azure Kubernetes'
    SPRING_DATASOURCE_URL: "jdbc:postgresql://pagopa-u-gpd-pgflex.postgres.database.azure.com:6432/apd?sslmode=require&prepareThreshold=0"
    SPRING_DATASOURCE_TYPE: "org.springframework.jdbc.datasource.SimpleDriverDataSource"
    SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
    SPRING_JPA_HIBERNATE_SHOW_SQL: "false"
    SCHEMA_NAME: "apd"
    CRON_JOB_SCHEDULE_ENABLED: "true"
    CRON_JOB_SCHEDULE_EXPRESSION_TO_VALID: "0 */10 * * * *"
    CRON_JOB_SCHEDULE_EXPRESSION_TO_EXPIRED: "0 */20 * * * *"
    AUX_DIGIT: 3
    LOG_LEVEL: "INFO"
    SQL_LOG_LEVEL: "INFO"
    SQL_BINDER_LOG_LEVEL: "INFO"
  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-u-connection-string'
    SPRING_DATASOURCE_PASSWORD: "db-apd-user-password"
    SPRING_DATASOURCE_USERNAME: "db-apd-user-name"
  keyvault:
    name: "pagopa-u-gps-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: true
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-debt-position
        tag: "0.6.16"
        pullPolicy: Always
      envConfig: {}
      envSecret: {}
