microservice-chart: &microservice-chart
  namespace: "gps"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-debt-position
    tag: "0.16.1-2-PAGOPA-3321-internal-pod"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  deployment:
    create: true
    replicas: 1 # (default) same as HPA minReplica
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress: &ingress
    create: true
    host: "weudev.gps.internal.dev.platform.pagopa.it"
    path: /pagopa-gpd-core/(.*)
    servicePort: 8080
    annotations:
      nginx.ingress.kubernetes.io/canary: 'false'
  serviceAccount:
    name: "gps-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources: &resources
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "640Mi"
      cpu: "0.5"
  autoscaling: &autoscaling
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 5 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "50"
      - type: metrics-api
        metadata:
          targetValue: "50" # milliseconds
          url: "https://weuuat.gps.internal.uat.platform.pagopa.it/pagopa-gpd-core/actuator/metrics/http.server.requests.percentile?tag=phi:0.99"
          valueLocation: "measurements.0.value"
    advanced:
      horizontalPodAutoscalerConfig:
        behavior:
          scaleDown:
            # https://github.com/kubernetes/enhancements/blob/master/keps/sig-autoscaling/853-configurable-hpa-scale-velocity/README.md#stabilization-window
            stabilizationWindowSeconds: 300
            policies:
              - type: Pods
                value: 1
                periodSeconds: 20
          scaleUp:
            stabilizationWindowSeconds: 0
            policies:
              - type: Pods
                value: 2
                periodSeconds: 20
  envConfig: &envConfig
    WEBSITE_SITE_NAME: 'pagopa-d-gpd-core-service'
    ENV: 'dev'
    SPRING_DATASOURCE_URL: "jdbc:postgresql://gpd-db.d.internal.postgresql.pagopa.it:5432/apd?sslmode=require&prepareThreshold=0&tcpKeepAlive=true"
    SPRING_DATASOURCE_TYPE: "com.zaxxer.hikari.HikariDataSource"
    SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
    SPRING_JPA_HIBERNATE_SHOW_SQL: "false"
    SCHEMA_NAME: "apd"
    CRON_JOB_SCHEDULE_ENABLED: "true"
    CRON_JOB_SCHEDULE_EXPRESSION_TO_VALID: "0 */10 * * * *"
    CRON_JOB_SCHEDULE_EXPRESSION_TO_EXPIRED: "0 */20 * * * *"
    CRON_JOB_SCHEDULE_HISTORY_ENABLED: "false"
    CRON_JOB_SCHEDULE_HISTORY_TRIGGER: "0 0 13 * * *"
    CRON_JOB_SCHEDULE_HISTORY_QUERY: "SELECT pp FROM PaymentPosition pp WHERE pp.status IN ('PAID', 'REPORTED', 'INVALID', 'EXPIRED') AND pp.lastUpdatedDate < ?1"
    CRON_JOB_SCHEDULE_HISTORY_PAGINATED: "true"
    CRON_JOB_SCHEDULE_HISTORY_QUERY_COUNT: "SELECT count(pp.id) FROM PaymentPosition pp WHERE pp.status IN ('PAID', 'REPORTED', 'INVALID', 'EXPIRED') AND pp.lastUpdatedDate < ?1"
    CRON_JOB_SCHEDULE_HISTORY_QUERY_PAGE_SIZE: "500"
    CRON_JOB_SCHEDULE_HISTORY_QUERY_INTERVAL: "30"
    CRON_JOB_SCHEDULE_HISTORY_SHEDLOCK_DEFAULTLOCKATMOSTFOR: "5m"
    CRON_JOB_SCHEDULE_HISTORY_SHEDLOCK_LOCKATMOSTFOR: "180m"
    CRON_JOB_SCHEDULE_HISTORY_SHEDLOCK_LOCKATLEASTFOR: "5m"
    GPD_ARCHIVE_SA_PP_TABLE: "paymentpositiontable"
    GPD_ARCHIVE_BATCH_OPERATION_SIZE: "100"
    AUX_DIGIT: "3"
    NODE_HOST: "https://api.dev.platform.pagopa.it"
    NODE_CHECK_POSITION_PATH: "/nodo/nodo-per-pm/v1/checkPosition"
    NODE_CONNECTION_TIMEOUT: "3000"
    SEND_HOST: "https://api.uat.notifichedigitali.it"
    NOTIFICATION_PRICE_PATH: "/delivery/v2.3/price/{paTaxId}/{noticeCode}"
    RETRY_MAX_DELAY: "2000"
    RETRY_MAX_ATTEMPTS: "1"
    LOG_LEVEL: "INFO"
    SQL_LOG_LEVEL: "ERROR"
    SQL_BINDER_LOG_LEVEL: "ERROR"
    MAX_DEBT_POSITIONS: "100"
    SERVICE_NAME: "pagopa-gpd-core"
    OTEL_SERVICE_NAME: "pagopa-gpd-core"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=dev"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_SAMPLER: "always_on"
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
  envSecret: &envSecret
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-d-connection-string'
    SPRING_DATASOURCE_PASSWORD: "db-apd-user-password"
    SPRING_DATASOURCE_USERNAME: "db-apd-user-name"
    NODE_SUBSCRIPTION_KEY: "gpd-d-node-subscription-key"
    SEND_SUBSCRIPTION_KEY: "gpd-d-send-subscription-key"
    GPD_ARCHIVE_SA_CONNECTION_STRING: "gpd-archive-d-sa-connection-string"
    OTEL_EXPORTER_OTLP_HEADERS: elastic-apm-secret-token
  keyvault:
    name: "pagopa-d-gps-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      type: header
      headerName: X-Canary
      headerValue: canary
      weightPercent: 0
      annotations:
        nginx.ingress.kubernetes.io/canary: 'true'
    image:
      repository: ghcr.io/pagopa/pagopa-debt-position
      tag: "0.16.0-2-hikari-switch"
      pullPolicy: Always
    envConfig: {}
    envSecret: {}
gpd-external:
  !!merge <<: *microservice-chart
  fullnameOverride: "gpd-core-external"
  ingress:
    !!merge <<: *ingress
  resources:
    !!merge <<: *resources
  envConfig:
    !!merge <<: *envConfig
  envSecret:
    !!merge <<: *envSecret
gpd-internal:
  !!merge <<: *microservice-chart
  fullnameOverride: "gpd-core-internal"
  ingress:
    !!merge <<: *ingress
    path: /pagopa-gpd-core-internal/(.*)
  resources:
    !!merge <<: *resources
  autoscaling:
    !!merge <<: *autoscaling
  envConfig:
    !!merge <<: *envConfig
  envSecret:
    !!merge <<: *envSecret
