name: Auto Deploy

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    types: [ closed ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    name: Call Azure Build Pipeline to Build and Deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # default skip bump versioning
      - name: Set as default skip bump versioning
        run: |
          echo "SEMVER=skip" >> $GITHUB_ENV

      - name: Set major
        run: |
          echo "SEMVER=major" >> $GITHUB_ENV
        if: ${{ contains(github.event.pull_request.labels.*.name, 'breaking-change') }}

      - name: Set minor
        run: |
          echo "SEMVER=minor" >> $GITHUB_ENV
        if: ${{ contains(github.event.pull_request.labels.*.name, 'enhancement') }}

      - name: Set patch
        run: |
          echo "SEMVER=patch" >> $GITHUB_ENV
        if: ${{ contains(github.event.pull_request.labels.*.name, 'bug') }}

      - name: Set skip
        run: |
          echo "SEMVER=skip" >> $GITHUB_ENV
        if: ${{ contains(github.event.pull_request.labels.*.name, 'ignore-for-release') }}

      # set repo
      - name: Set GPD repo
        run: |
          echo "REPO=gpd" >> $GITHUB_ENV
        if: ${{ contains(github.event.pull_request.labels.*.name, 'gpd') }}

      - name: Set Payments repo
        run: |
          echo "REPO=payments" >> $GITHUB_ENV
        if: ${{ contains(github.event.pull_request.labels.*.name, 'payments') }}

      - name: Set Reporting Analysis repo
        run: |
          echo "REPO=reporting-analysis" >> $GITHUB_ENV
        if: ${{ contains(github.event.pull_request.labels.*.name, 'reporting-analysis') }}

      - name: Set Reporting Batch repo
        run: |
          echo "REPO=reporting-batch" >> $GITHUB_ENV
        if: ${{ contains(github.event.pull_request.labels.*.name, 'reporting-batch') }}

      - name: Set Reporting Service repo
        run: |
          echo "REPO=reporting-service" >> $GITHUB_ENV
        if: ${{ contains(github.event.pull_request.labels.*.name, 'reporting-service') }}


      - name: Azure Pipelines Action - Jversion
        uses: jacopocarlini/azure-pipelines@v1.3
        with:
          azure-devops-project-url: https://dev.azure.com/pagopaspa/pagoPA-projects
          azure-pipeline-name: 'pagopa-debt-position.deploy'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          azure-template-parameters: '{"ENV": "dev", "SEMVER": "${{env.SEMVER}}", "TEST": "true", "REPOSITORY":"${{env.REPO}}"}'
          azure-pipeline-variables: '{"system.debug": "true"}'

